%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\ESSplace\Simulation\BESS\LV_RES\All_data.xlsx
%    Worksheet: Max_Voltage
%
% Auto-generated by MATLAB on 10-Apr-2020 13:35:53

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Max_Voltage";
opts.DataRange = "A1:J100";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Alldata = readtable("D:\ESSplace\Simulation\BESS\LV_RES\All_data.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts